name: Feedback
description: Use this template to provide feedback on our metadata / Nutzen Sie diese Vorlage, um Feedback zur unserer Metadata zu geben
title: "Feedback: "
labels: ["feedback"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank für Ihr Feedback! Ihre Rückmeldung hilft uns, die Materialien gezielt zu verbessern.
        
  - type: dropdown
    id: section
    attributes:
      label: Module/Modul
      description: Which module have you issues? / Mit welchem Modul hast du Probleme?
      options:
        - Cat_core
        - Synthesis
        - Characterization
        - Reaction
        - Simulation
    validations:
      required: true

  - type: input
    id: label
    attributes:
      label: Label
    validations:
      required: true

  - type: input
    id: parents
    attributes:
      label: Parent(s)
    validations:
      required: true

  - type: dropdown
    id: mandatory_or_not
    attributes:
      label: Mandatory, Recommended, Optional?
      options:
        - Mandatory
        - Recommended
        - Optional
    validations:
      required: true

  - type: input
    id: field_type
    attributes:
      label: Field Type
    validations:
      required: true

  - type: input
    id: allowed_entries
    attributes:
      label: Number of Allowed Entries
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Note
      description: What would you like to tell us? / Was möchten Sie uns mitteilen?
      placeholder: Bitte beschreiben Sie Ihr Feedback so konkret wie möglich.
    validations:
      required: true
